os: linux
dist: focal
language: node_js

env:
  global:
    - NG_CLI_ANALYTICS="ci"

node_js:
  - node

addons:
  chrome: stable

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

script:
  - npm run build:lib
  - npm run test:ci
  - ng serve &
  - $(npm bin)/wait-on http-get://localhost:4200/#
  - npm run e2e
  - kill $(jobs -p) || true
